S02 us31 slider
WildCodeSchool-2024-09/JS-RemoteFR-Vert-CrewCodeIle-Sloubi-P2 pull request #56
Opened 2024-11-15 08:22 UTC by Remi-Dubus

Add discovery and top 10 slider to HomePage.

2024-11-15 08:34 UTC, AmandineGrardLaurent approved these changes

2024-11-15 08:35 UTC, JP-Lefever approved these changes

2024-11-15 08:56 UTC, victorSanLopez approved these changes

2024-11-15 10:15 UTC, ioayoub requested changes
client/src/components/cardSlider/CardSlider.tsx to optimize

2024-11-15 11:37 UTC, JP-Lefever approved these changes

2024-11-15 12:21 UTC, victorSanLopez approved these changes

2024-11-15 12:57 UTC, AmandineGrardLaurent approved these changes

2024-11-15 13:59 UTC, AmandineGrardLaurent submitted a review, later dismissed

2024-11-15 14:33 UTC, JP-Lefever submitted a review, later dismissed

2024-11-16 13:13 UTC, victorSanLopez approved these changes

2024-11-17 18:07 UTC, victorSanLopez approved these changes

2024-11-18 14:43 UTC, JP-Lefever submitted a review, later dismissed

2024-11-18 14:45 UTC, AmandineGrardLaurent submitted a review, later dismissed

2024-11-19 08:17 UTC, ioayoub requested changes

2024-11-19 08:17 UTC, ioayoub commented on client/src/pages/homePage/HomePage.tsx
> +    ? boardGames.filter(
Tu peux optimiser ici en utilisant un tableau, il faut également une indication sur la provenance de ces valeurs. 
A quoi correspondent-elles ?

2024-11-19 08:17 UTC, ioayoub commented on client/src/components/cardSlider/CardSlider.tsx
> +          <CardGame
Trop de logique dans le JSX ici, séparez l'affichage de la logique pour une meilleure lisibilité.
Astuce: ton jsx doit simplement recevoir un tableau avec 3 CardGames pour éviter toutes ces répétitions.

2024-11-19 14:56 UTC, JP-Lefever approved these changes

2024-11-19 14:56 UTC, AmandineGrardLaurent approved these changes

2024-11-20 13:48 UTC, ioayoub approved these changes

2024-11-20 13:50 UTC, AmandineGrardLaurent approved these changes

2024-11-20 13:50 UTC, victorSanLopez approved these changes

2024-11-20 13:52 UTC, JP-Lefever approved these changes

2024-11-20 13:55 UTC, merged