S02us48 filter
WildCodeSchool-2024-09/JS-RemoteFR-Vert-CrewCodeIle-Sloubi-P2 pull request #57
Opened 2024-11-19 15:50 UTC by JP-Lefever

2024-11-19 17:00 UTC, ioayoub requested changes

2024-11-19 17:00 UTC, ioayoub commented on client/src/pages/libraryPage/LibraryPage.tsx
> +        {filterType !== ""
ce n'est pas nécessaire d'ajouter cette condition ici puisque une chaine de caractères vide renvoi toujours vrai.
exemple : 
```js
const firstName = "toto";
console.log(firstName.includes("")) // true
```

2024-11-20 13:49 UTC, AmandineGrardLaurent approved these changes

2024-11-20 13:50 UTC, victorSanLopez approved these changes

2024-11-20 14:43 UTC, victorSanLopez approved these changes

2024-11-20 15:40 UTC, ioayoub approved these changes

2024-11-20 15:42 UTC, merged